### ISSUE TITLE
Handling of sub-repositories

### ISSUE THREAD

**Issue by tobstarr** [constabulary/gb-vendor#2] opened 2015-05-13 20:26 UTC
What is the recommended way to deal with nested git repositories in `src/vendor`. Vendoring with `gb-vendor` is currently also storing the `.git` directories of e.g. git based libraries (as it uses `go get`) but those would be ignored by git by default and not make it into the repository.

One could just delete all `.git` dirs in `vendor/src` but there should be at least some kind of reference to which version of the library was actually vendored. Also a flag to update an existing library would make sense (e.g. just add a `-u` flag which gets added to the `go get` command if present)?

**Comment by tobstarr** [comment] 2015-05-13 20:35
I opened a PR for the update flag: https://github.com/constabulary/gb-vendor/pull/3

**Comment by davecheney** [comment] 2015-05-26 08:23
Duplicate of constabulary/gb#130

**Closed by davecheney** 2015-05-26 08:23 UTC
